### ISSUE TITLE
update DNS for cssbeautify.com

### ISSUE THREAD

**Issue by fbender** [senchalabs/cssbeautify#43]
Since GitHub changed its IP addresses for custom domains, cssbeautify.com is no longer reachable. 

Also, would be nice if the gh-pages would be updated ;)

**Comment by mockturtl** [comment]
:+1:

**Comment by re4jh** [comment]
:+1:

**Comment by nicolasbettag** [comment]
:+1:

**Comment by re4jh** [comment]
forked: [cssbeautify.jonashess.de](http://cssbeautify.jonashess.de/)

**Comment by ariya** [comment]
Please use http://www.senchalabs.org/cssbeautify/.
